server:
  port: 8081

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

via_cep:
  client:
    address:
      url: https://viacep.com.br/ws
