server:
  port: 8081

# limit size of received files
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

aws:
  credentials:
    access-key: test_access_key
    secret-key: test_secret_access_key
  s3:
    endpoint: http://s3.localhost.localstack.cloud:4566/
  dynamodb:
    endpoint: http://localhost.localstack.cloud:4566/
  sqs:
    endpoint: http://localhost:4566/000000000000
  region: us-east-1

# log everything
logging:
  level:
    root=debug:

via_cep:
  client:
    address:
      url: https://viacep.com.br/ws
